# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
        ('cliente', '0001_initial'),
        ('Activos', '0001_initial'),
        ('reserva', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFactura', models.DateTimeField(default=django.utils.timezone.now)),
                ('horaEntrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('horaSalida', models.TimeField(auto_now=True, null=True, verbose_name='Hora de Entrada')),
                ('kilometraje', models.PositiveSmallIntegerField(verbose_name='Kilometraje')),
                ('kmProx', models.PositiveSmallIntegerField(verbose_name='Proximo Kilometraje')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total a pagar')),
                ('tiempoEstimado', models.CharField(blank=True, max_length=35, verbose_name='Tiempo estimado')),
                ('idFormaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.formapago', verbose_name='Forma de Pag')),
                ('idPlaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.plaza', verbose_name='Plaza usada')),
                ('idVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Factura de Servicio',
                'verbose_name_plural': 'Facturas de Servicios',
                'ordering': ('fechaFactura',),
            },
        ),
        migrations.CreateModel(
            name='ServicioTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ('descripcion',),
            },
        ),
        migrations.CreateModel(
            name='ServicioTrabDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedulaEmp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado', verbose_name='Empleado')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle Trabajador en Factura Servicio',
                'verbose_name_plural': 'Detalles Trabajador en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioTipoDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
                ('idServiceTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciotipo', verbose_name='Servicio aplicado')),
            ],
            options={
                'verbose_name': 'Detalle Tipo de Servicio en Factura',
                'verbose_name_plural': 'Detalles Tipo de Servicios en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioProdDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Cantidad')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.producto', verbose_name='Producto')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle Producto en Factura Servicio',
                'verbose_name_plural': 'Detalles Producto en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioMaquDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMaquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.maquinaria', verbose_name='Maquinaria')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle Maquinaria en Factura',
                'verbose_name_plural': 'Detalles de Maquinarias en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioEquiDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEquipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.equipo', verbose_name='Equipo')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
            ],
            options={
                'verbose_name': 'Detalle Equipo en Factura Servicio',
                'verbose_name_plural': 'Detalles Equipos en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaRecogida', models.DateTimeField()),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
                ('idTranspor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.transportadorcualificado', verbose_name='Transportador')),
            ],
            options={
                'verbose_name': 'Detalle Transportador en Factura Servicio',
                'verbose_name_plural': 'Detalles Transportadores en Facturas',
                'ordering': ('idService',),
            },
        ),
        migrations.CreateModel(
            name='ServicioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Calificación')),
                ('opinion', models.TextField(default='Sin opinión', max_length='150', verbose_name='Opinión')),
                ('cedulaCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.serviciocab', verbose_name='Factura de Servicio')),
            ],
            options={
                'verbose_name': 'Calificación de Servicio',
                'verbose_name_plural': 'Calificaciones de Servicios',
                'ordering': ('idService',),
            },
        ),
    ]
