# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipo de Equipos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='MaquinariaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Maquinaria',
                'verbose_name_plural': 'Tipo de Maquinarias',
                'ordering': ('modelo',),
            },
        ),
        migrations.CreateModel(
            name='ProductoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipo de Productos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Cantidad de Producto')),
                ('idProductoTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.productotipo', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Tipo de Maquinaria')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripción')),
                ('fechaAdquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('EstadoReponer', models.CharField(choices=[('F', 'EN USO'), ('V', 'REPONER')], default='F', max_length=1, verbose_name='Estado')),
                ('EstadoMantenimiento', models.CharField(choices=[('F', 'NO REQUIERE MANTENIMIENTO'), ('A', 'REQUIERE MANTENIMIENTO')], default='F', max_length=1, verbose_name='Estado de Mantenimiento')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('idMaquModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.maquinariamodelo', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Máquinas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre de Equipo')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripción')),
                ('estadoReponer', models.CharField(choices=[('F', 'EN USO'), ('V', 'REPONER')], default='F', max_length=1, verbose_name='Estado')),
                ('idEquipTipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.equipotipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ('nombre',),
            },
        ),
    ]
