# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedulaCliente', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=10, unique=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nombres', '-apellidos'),
            },
        ),
        migrations.CreateModel(
            name='VehiculoCarroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Carrocería de Vehículo')),
            ],
            options={
                'verbose_name': 'Carrocería de Vehículo',
                'verbose_name_plural': 'Carrocerías de Vehículos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='VehiculoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=35, unique=True, verbose_name='Marca de Vehículo')),
            ],
            options={
                'verbose_name': 'Marca de Vehículo',
                'verbose_name_plural': 'Marcas de Vehículos',
                'ordering': ('marca',),
            },
        ),
        migrations.CreateModel(
            name='VehiculoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=35, unique=True, verbose_name='Modelo de Vehículo')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.vehiculomarca', verbose_name='Marca de Vehículo')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'ordering': ('modelo',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('añoFabri', models.DateField(verbose_name='Año de Fabricación')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('cedulaCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Propietario')),
                ('idCarroceria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.vehiculocarroceria', verbose_name='Carrocería')),
                ('idModelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.vehiculomodelo', verbose_name='Modelo vehicular')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ('idCarroceria',),
            },
        ),
    ]
