# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activos', '0001_initial'),
        ('personal', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=25, unique=True, verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pagos',
                'ordering': ('forma',),
            },
        ),
        migrations.CreateModel(
            name='VentaCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precioTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total a Pagar')),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cambio')),
                ('cedulaCliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('cedulaEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado', verbose_name='Empleado')),
                ('idFormaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.formapago', verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='VentaDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Monto')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Activos.producto', verbose_name='Producto')),
                ('idVentaCab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.ventacab', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
                'ordering': ('idVentaCab',),
            },
        ),
    ]
