# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=35, unique=True, verbose_name='Función')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sueldo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ('funcion',),
            },
        ),
        migrations.CreateModel(
            name='ContratoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=40, unique=True, verbose_name='Tipo de Contrato')),
                ('tiempo', models.CharField(max_length=35, verbose_name='Tiempo de Contrato')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
                'ordering': ('contrato',),
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedulaEmp', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=10, unique=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('nombres', '-apellidos'),
            },
        ),
        migrations.CreateModel(
            name='TransportadorCualificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentoAvalador', models.FileField(upload_to='Permisos/', verbose_name='Permiso Institucional Avalador')),
                ('Estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cedulaEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado', verbose_name='Cédula de Empleado')),
            ],
            options={
                'verbose_name': 'Transportador Cualificado',
                'verbose_name_plural': 'Transportadores Cualificados',
            },
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContrato', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField(verbose_name='Día de comienzo de actividades laborales')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.cargo', verbose_name='Cargo a ejercer')),
                ('cedulaEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado', verbose_name='Nombres de Acreedor')),
                ('tipoContratacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.contratotipo', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ('fechaContrato',),
            },
        ),
    ]
