# Generated by Django 4.0.7 on 2022-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plaza',
                'verbose_name_plural': 'Plazas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
                ('horaIngreso', models.TimeField(verbose_name='Hora de Ingreso')),
                ('diaIngreso', models.DateField(verbose_name='Día de Ingreso')),
                ('retiroDomicilio', models.BooleanField(default=False, verbose_name='Retiro a Domicilio')),
                ('cedulaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('cedulaEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado', verbose_name='Empleado')),
                ('idPlaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.plaza', verbose_name='Plaza a reservar')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ReservaTipoDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.reserva', verbose_name='Reserva')),
                ('idTranspor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.transportadorcualificado', verbose_name='Transportador')),
            ],
            options={
                'verbose_name': 'Detalle de Reservación',
                'verbose_name_plural': 'Detalles de Reservaciones',
                'ordering': ('id',),
            },
        ),
    ]
